# Data paths
metadata_csv: data/burrowing_owl_dataset/metadata.csv
data_path: data/burrowing_owl_dataset/audio
hf_cache_path: data/burrowing_owl_dataset/cache/metadata.hf

# Required Variables
COMET_PROJECT_NAME: "whoot"
CUDA_VISIBLE_DEVICES: "0" #"0,1"
SUBPROJECT_NAME: 
DATASET_NAME: 