[project]
name = "whoot"
dynamic = ["version"]
description = "Tools for capturing, analyzing, and parsing audio data"
readme = "README.md"
requires-python = ">= 3.10.0, < 3.13.0"
dependencies = [
    "librosa>=0.10.2.post1",
    "numba==0.61.0",
    "pandas>=2.3.0",
    "pydub>=0.25.1",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.0",
    "soundfile>=0.13.1",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "pylint>=3.3.7",
    "flake8-docstrings>=1.7.0",
]

[tool.setuptools.dynamic]
version = {attr = "whoot.__version__"}

[project.optional-dependencies]
cpu = [
  "torch>=2.7.0",
  "torchaudio>=2.8.0",
  "torchvision>=0.22.0",
]
cu128 = [
  "torch>=2.7.0",
  "torchaudio>=2.8.0",
  "torchvision>=0.22.0",
]
model-training = [
  "datasets>=3.5.1,<4.0.0",
  "timm>=1.0.15",
  "pyha-analyzer@git+https://github.com/UCSD-E4E/pyha-analyzer-2.0.git@support_whoot",
  "comet-ml>=3.43.2",
]

perch = [
  "perch-hoplite>=0.1.0",
  "tensorflow-hub>=0.16.1",
  "tensorflow[and-cuda]>=2.20.0",
]

notebooks = [
  "ipykernel>=6.29.5",
  "ipywidgets>=8.1.6",
  "matplotlib>=3.10.6",
  "seaborn>=0.13.2",
]
birdnet = [
    "birdnet>=0.1.7",
]


[packages.index]
cu128 = "https://download.pytorch.org/whl/cu128"

[tool.setuptools]
packages = ["make_model", "assess_birdnet", "whoot_model_training", "data_downloader"]

[tool.uv.sources]
pyha-analyzer = { git = "https://github.com/UCSD-E4E/pyha-analyzer-2.0.git", branch = "support_whoot" }

